import * as XLSX from 'xlsx'

export function exportToExcel<T extends object>(
  data: T[],
  filename: string,
  sheetName = 'Report',
): void {
  const worksheet = XLSX.utils.json_to_sheet(data)
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName)
  XLSX.writeFile(workbook, `${filename}.xlsx`)
}

export function exportToPDF(title: string, content: string): void {
  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: Inter, sans-serif; padding: 40px; color: #1e293b; }
          h1 { color: #1e3a5f; border-bottom: 2px solid #1e3a5f; padding-bottom: 8px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
          th { background: #f1f5f9; }
          .footer { margin-top: 40px; color: #64748b; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        ${content}
        <div class="footer">Generated by Cell Craft ERP — ${new Date().toLocaleDateString()}</div>
      </body>
    </html>
  `)
  printWindow.document.close()
  printWindow.print()
}
